name: Deploy to Firebase Hosting on develop
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    uses: ./.github/workflows/firebase-hosting-deploy.yml
    with:
      channelId: beta
    secrets: inherit