name: Deploy to Firebase Hosting
'on':
  workflow_call:
    inputs:
      channelId:
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build web --release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_UI_EXPERIMENT_DEMO }}
          channelId: ${{ inputs.channelId }}
          projectId: flutter-ui-experiment-demo
