name: Deploy to Firebase Hosting on main
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    uses: ./.github/workflows/firebase-hosting-deploy.yml
    with:
      channelId: live
    secrets: inherit